# Generated by Django 4.1.7 on 2023-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(auto_now=True)),
                ('gender', models.CharField(max_length=250)),
                ('mob', models.IntegerField()),
                ('mail', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('actype', models.CharField(max_length=250)),
                ('mp', models.CharField(max_length=250)),
            ],
        ),
    ]
